In [1]:
#Library
import numpy as np

In [2]:
#Setting parameters gamma and alpha to Q-Learning
gamma = 0.75
alpha = 0.9

In [3]:
# Part 1 - Environment Definition
location_to_state = {'A': 0,
                     'B': 1,
                     'C': 2,
                     'D': 3,
                     'E': 4,
                     'F': 5,
                     'G': 6,
                     'H': 7,
                     'I': 8,
                     'J': 9,
                     'K': 10,
                     'L': 11}


In [4]:
actions = [0,1,2,3,4,5,6,7,8,9,10,11]

In [15]:
#Rewards
R = np.array([[0,1,0,0,0,0,0,0,0,0,0,0],
              [1,0,1,0,0,1,0,0,0,0,0,0],
              [0,1,0,0,0,0,1,0,0,0,0,0],
              [0,0,0,0,0,0,0,1,0,0,0,0],
              [0,0,0,0,0,0,0,0,1,0,0,0],
              [0,1,0,0,0,0,0,0,0,1,0,0],
              [0,0,1,0,0,0,1,1,0,0,0,0],
              [0,0,0,1,0,0,1,0,0,0,0,1],
              [0,0,0,0,1,0,0,0,0,1,0,0],
              [0,0,0,0,0,1,0,0,1,0,1,0],
              [0,0,0,0,0,0,0,0,0,1,0,1],
              [0,0,0,0,0,0,0,1,0,0,1,0]])


In [19]:
# Part 2 - Creating the AI solution with Q-Learning
Q=np.array(np.zeros([12,12]))
for i in range(1000):
    current_state=np.random.randint(0,12)
    playable_actions=[]
    for j in range(12):
        if R[current_state, j]>0:
            playable_actions.append(j)
    next_state=np.random.choice(playable_actions)
    TD=R[current_state, next_state]+ gamma* Q[next_state, np.argmax(Q[next_state],)]-Q[current_state, next_state]
    Q[current_state, next_state]= Q[current_state, next_state]+alpha*TD 

In [17]:
#Part 3 - Results (Getting in production)
#Rewards
R = np.array([[0,1,0,0,0,0,0,0,0,0,0,0],
              [1,0,1,0,0,1,0,0,0,0,0,0],
              [0,1,0,0,0,0,1,0,0,0,0,0],
              [0,0,0,0,0,0,0,1,0,0,0,0],
              [0,0,0,0,0,0,0,0,1,0,0,0],
              [0,1,0,0,0,0,0,0,0,1,0,0],
              [0,0,1,0,0,0,1000,1,0,0,0,0],
              [0,0,0,1,0,0,1,0,0,0,0,1],
              [0,0,0,0,1,0,0,0,0,1,0,0],
              [0,0,0,0,0,1,0,0,1,0,1,0],
              [0,0,0,0,0,0,0,0,0,1,0,1],
              [0,0,0,0,0,0,0,1,0,0,1,0]])


In [23]:
print(Q.astype(int))

[[   0 1675    0    0    0    0    0    0    0    0    0    0]
 [1256    0 2235    0    0 1246    0    0    0    0    0    0]
 [   0 1661    0    0    0    0 2982    0    0    0    0    0]
 [   0    0    0    0    0    0    0 2234    0    0    0    0]
 [   0    0    0    0    0    0    0    0  706    0    0    0]
 [   0 1661    0    0    0    0    0    0    0  930    0    0]
 [   0    0 2237    0    0    0 3975 2233    0    0    0    0]
 [   0    0    0 1651    0    0 2977    0    0    0    0 1651]
 [   0    0    0    0  530    0    0    0    0  941    0    0]
 [   0    0    0    0    0 1246    0    0  702    0 1253    0]
 [   0    0    0    0    0    0    0    0    0  936    0 1672]
 [   0    0    0    0    0    0    0 2230    0    0 1239    0]]


In [35]:
state_to_location = {state: location for location, state in location_to_state.items()}

In [36]:
def route(starting_location, ending_location):
    route = [starting_location]
    next_location = starting_location
    while (next_location != ending_location):
        starting_state = location_to_state[starting_location]
        next_state = np.argmax(Q[starting_state])
        next_location = state_to_location[next_state]
        route.append(next_location)
        starting_location = next_location
    return route

In [38]:
#Printing the final route
print('Route: ')
route('E','G')

Route: 


['E', 'I', 'J', 'K', 'L', 'H', 'G']

In [39]:
#Printing the final route
print('Route: ')
route('A','G')

Route: 


['A', 'B', 'C', 'G']

In [40]:
#Printing the final route
print('Route: ')
route('K','G')

Route: 


['K', 'L', 'H', 'G']

In [41]:
def best_route(starting_location, intermediary_location, ending_location):
    return route(starting_location, intermediary_location) + route(intermediary_location, ending_location)[1:]

best_route('E', 'K', 'G')

['E', 'I', 'J', 'K', 'L', 'H', 'G']